services:
  - type: web
    name: alcohol-label-verifier
    env: python
    region: oregon
    plan: free
    buildCommand: apt-get update && apt-get install -y tesseract-ocr && pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn run:app --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.10.0